# This workflow is based on the Deployment (cd.yml) Starter Workflow
name: Deployment
on:
  workflow_run:
    workflows: ["Integration"]
    branches: ["main", "develop"] # remove / add branches that are not needed / needed
    types:
      - completed

jobs:
  deploy-from-develop:
    name: Deploy 'develop' to ${{ matrix.target }}
    if: github.event.workflow_run.head_branch == 'develop'

    strategy:
      fail-fast: false
      matrix:
        target: [azure, integration, test]

    # check documentation via https://github.com/stgallerkb/workflows/blob/main/docs/k8s-deploy.md
    uses: stgallerkb/workflows/.github/workflows/k8s-deploy.yml@v1
    secrets: inherit
    with:
      environment: ${{ matrix.target }}

  deploy-from-main:
    name: Deploy 'main' to ${{ matrix.target }}
    if: github.event.workflow_run.head_branch == 'main'

    strategy:
      fail-fast: false
      matrix:
        target: [azure, integration, test, production]

    # check documentation via https://github.com/stgallerkb/workflows/blob/main/docs/k8s-deploy.md
    uses: stgallerkb/workflows/.github/workflows/k8s-deploy.yml@v1
    secrets: inherit
    with:
      environment: ${{ matrix.target }}
