name: CI
on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: stgallerkb/pipeline-setup-action@v1.2
        with:
          java-version: "11"
          azure-npm-user: ${{ secrets.AZURE_NPM_USER }}
          azure-npm-secret: ${{ secrets.AZURE_NPM_PAT }}
          azure-npm-registry: ${{ secrets.AZURE_NPM_REGISTRY }}

      - run: npm run lint
      - run: npm run test

  build:
    needs: [check]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: stgallerkb/pipeline-setup-action@v1.2
        with:
          java-version: "11"
          azure-npm-user: ${{ secrets.AZURE_NPM_USER }}
          azure-npm-secret: ${{ secrets.AZURE_NPM_PAT }}
          azure-npm-registry: ${{ secrets.AZURE_NPM_REGISTRY }}

      - run: npm run build

      - name: semver - production
        if: github.ref == 'refs/heads/main'
        run: npm run release

      - name: semver - prerelease
        if: github.ref != 'refs/heads/main'
        run: npm run release-next

      - name: move compiled frontend to backend
        run: |
          mkdir -p ./backend/src/main/resources/public/web-component
          cp -r ./frontend/dist/* ./backend/src/main/resources/public/web-component

      - name: gradle test build
        run: |
          cd backend
          gradle test jacocoTestReport build
          cd ..
        env:
          AZURE_DEVOPS_REPO_PAT: ${{ secrets.AZURE_DEVOPS_REPO_PAT_GITHUB }}

      - uses: docker/setup-buildx-action@v2
        if: github.ref == 'refs/heads/main' || github.ref != 'refs/heads/develop'

      - uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main' || github.ref != 'refs/heads/develop'
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/main' || github.ref != 'refs/heads/develop'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/rmwp-table:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
