name: "Manual Deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "azure"
        type: environment

jobs:
  deploy:
    name: Deployment
    # check documentation via https://github.com/stgallerkb/workflows/blob/main/docs/k8s-deploy.md
    uses: stgallerkb/workflows/.github/workflows/k8s-deploy.yml@v1
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
